### ISSUE TITLE
`merge` terminology

### ISSUE THREAD

**Issue by martbern** [Aarhus-Psychiatry-Research/psycop-ml-utils#30]
See comments in #27.

**Comment by martbern** [comment]
Hmm, upon review I actually still prefer `add_predictor` and `add_outcome`, because they're more readable.

Yes, it is less abstracted/general than `lookbehind_merge` and `lookahead_merge`, but I think that's abstracting too far for our current use-case. @KennethEnevoldsen, we can chat about it f2f at some point?

**Comment by KennethEnevoldsen** [comment]
Sure we can.

But I will give you an answer here as well:
When you read `add_predictor` then you immediately think "how" (I also think "what" predictor?) as it does not tell you what the function does but only that you intend to use the output of the function as a predictor. Instead of with the lookaround you would think "why" which I generally think is better as this is easily resolved by a comment.

That being said you could keep the add_predictor and add_outcome it would be transparent from the class what it was, but I don't feel like that is the case.

Changing the add_col to lookaround_merge() I assume we can agree on though.
